"""new fields in user model

Revision ID: 658504acbe69
Revises: ce95b145af9c
Create Date: 2018-12-06 23:47:28.609252

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '658504acbe69'
down_revision = 'ce95b145af9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
