"""followers

Revision ID: caad48738749
Revises: 658504acbe69
Create Date: 2018-12-07 02:12:23.180932

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'caad48738749'
down_revision = '658504acbe69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
                    sa.Column('follower_id', sa.Integer(), nullable=True),
                    sa.Column('followed_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
